apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: load-generator
  name: load-generator
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - while sleep 0.01; do wget -q -O- http://php-apache; done
      image: busybox
      name: load-generator
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never